name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: test
      shell: bash
      env:
        SUPER_SECRET: ${{ secrets.REACT_APP_SUPABASE_URL }}
        TEST_ENV: 123
      run: |
        echo "$SUPER_SECRET"
        echo "$TEST_ENV"

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      env:
        REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
        REACT_APP_SUPABASE_KEY: ${{ secrets.REACT_APP_SUPABASE_KEY }}
        CI: false
      run: |
        npm install
        npm run build
        gh-pages -d build
        echo "$REACT_APP_SUPABASE_URL"
        echo "GITHUB_REPOSITORY_SLUG=$GITHUB_REPOSITORY_SLUG"

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
